apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-service-app
  labels:
    app: node-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : node-service-app
  template:
    metadata:
      labels:
        app: node-service-app
    spec:
      containers:
      - name: node-service-app
        image: cs6400/node-service:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 9002

---

kind: Service
apiVersion: v1
metadata:
  name:  node-service-svc
spec:
  selector:
    app:  node-service-app
  ports:
  - port:  80
    targetPort:  9002
